### ISSUE TITLE
Password changed?

### ISSUE THREAD

**Issue by MuriloChianfa** [tomatophp/tomato-roles#1]
hello, im testing your project, but when i install plugins, the password typed for the administrator account is:
https://github.com/tomatophp/tomato-roles/blob/03c143a381ac6dc306be789a5b47d62810468541/config/tomato-roles.php#L23
but this password not match with:
https://github.com/tomatophp/tomato-roles/blob/03c143a381ac6dc306be789a5b47d62810468541/database/migrations/2023_01_01_114555_fill_default_admin_user_and_permissions.php#L44
its right?
in console output its wrong,
![image](https://github.com/tomatophp/tomato-roles/assets/60560085/89931573-737a-4508-873d-247894c7aba6)
but in the docs its right
![image](https://github.com/tomatophp/tomato-roles/assets/60560085/d0e2b6ac-ec43-430e-83c0-5bdd2026e311)

**Comment by LukasCCB** [comment]
Checking in `DeveloperController.php` from `TomatoPHP\TomatoRoles`
I found this, maybe can help you to check `session()->put('dev_password', Crypt::encrypt($request->get('password')));`

The value of "QTS@2022" is just a default value if  "DEVELOPER_PASSWORD" is missing in your env file. 
Just an interpretation error when typing the password in this file, to fill it in if it is missing. however, it is in fact only symbolic.

**Comment by fadymondy** [comment]
please check these docs
https://docs.tomatophp.com/plugins/tomato-roles/developer-gate

you are speaking about Developer Gate not the main password of the tomato roles

but on the command line, I think it needs to fix I will check it.
