### ISSUE TITLE
Deleting a user is very confusing

### ISSUE THREAD

**Issue by rabol** [tomatophp/tomato-roles#2]
When you try to delete a user in the admin panel you will get this message:

![Screenshot 2023-10-09 at 22 03 11](https://github.com/tomatophp/tomato-logs/assets/1177191/0ada40d6-a697-4495-ae62-b9ff48da5e65)

that indicate that you will be given a second option... no, it will delete the user!

**Comment by fadymondy** [comment]
Okay, we can change it to alert.

**Comment by rabol** [comment]
IMHO, a more traditional 'are you sure' would be better
it is as if the 'head line' removes the focus

**Comment by fadymondy** [comment]
fixed in v1.1.7

<img width="542" alt="Screenshot 2024-04-25 at 1 15 28 PM" src="https://github.com/tomatophp/tomato-roles/assets/11937812/bd19ba8f-95f7-461c-a49e-2803c4e5c2ec">
